Repository briandfoy/cpan-audit, pull requests merged in 2023-04, with the labels that each got.

#43 document dependencies
  util/generate
Labels: Type: documentation

#46 command_deps wants a directory, not any old path
  lib/CPAN/Audit.pm
Labels: Type: enhancement, Status: needs testing, Priority: low

#49 Straight-up copy/paste `dumper` from `Mojo::Util`
  util/generate
Labels: Type: enhancement, Priority: low
